use_frameworks!

platform :ios, '10.0'

target 'YBTableViewController_Example' do
  pod 'YBTableViewController', :path => '../'

  target 'YBTableViewController_Tests' do
    inherit! :search_paths

    
  end
end
